### ISSUE TITLE
Add a demo

### ISSUE THREAD

**Issue by karanrajpal14** [Websilk/Selector#1]
Hey, it would be great if you could add a demo of this to showcase the functionality. A JSFiddle perhaps?

**Comment by markentingh** [comment]
absolutely. I'll build a demo right away.

**Comment by markentingh** [comment]
I'm currently setting up a home for selector.js on a permanent public CDN via [https://github.com/jsdelivr/jsdelivr/pull/17506](https://github.com/jsdelivr/jsdelivr/pull/17506) and will be able to publish the JSFiddle [](https://jsfiddle.net/markentingh/L2o0qrwy/25/). In the meantime, I'm using jQuery to make the JSFiddle, and will simply switch out jQuery with selector.js once jsdelivr approves the project on their CDN.

**Comment by karanrajpal14** [comment]
That's great. Close the issue once you're done. Can't wait to try this in my personal projects 😄

**Comment by Turqueso** [comment]
jsdeliver merged now, tried the demo with the CDN but seems like teleport example doesn't work
https://jsfiddle.net/L2o0qrwy/61/ <-- with selectorjs

**Comment by markentingh** [comment]
Yes, I've committed some fixes and just released a new beta version (0.9.1), which should be auto-updated on the CDN. I've tested the demo locally using this new version. 

There is still much work to do before we get to version 1.0, but so far, I've been using selector.js on my personal projects for over a year now and have built it to the point where I can release it as open source.

**Comment by markentingh** [comment]
[Demo](https://jsfiddle.net/markentingh/L2o0qrwy/) is live!
